default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("/apiRAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: meetup_clone_demo_app_development

test:
  <<: *default
  database: meetup_clone_demo_app_test

production:
  <<: *default